name: cellpose
channels:
  - conda-forge
  - defaults
dependencies:
  - python>3.10
  - pip
  - imagecodecs
  - pip:
    - cellpose
    - fastremap
    - llvmlite
    - natsort
    - numba>0.5
    - opencv-python
    - opencv-python-headless
    - pandas
    - pillow
    - python-dateutil
    - pytz
    - scipy
    - setuptools
    - six
    - tifffile
    - torch>1.1
    - tqdm
    - typing-extensions
