FROM --platform=${BUILDPLATFORM}  cloneid-module3-base_jdk21-amd64:latest

ARG IMAGE_BUILD_ARCH=amd64
ARG IMAGE_BUILD_INFO="Cloneid Module3"
ARG IMAGE_BUILD_NAME="cloneid-module3"
ARG IMAGE_BUILD_DATE
ARG IMAGE_BUILD_VERSION="1.0𝛂"
ARG IMAGE_AUTHOR_FNAME="Daniel"
ARG IMAGE_AUTHOR_LNAME="Hannaby"
ARG IMAGE_AUTHOR_EMAIL="<legwork_02land@icloud.com>"
ARG IMAGE_VENDOR="Moffitt"
ARG IMAGE_LICENSE="MIT"
ARG IMAGE_TITLE="${IMAGE_BUILD_NAME}:latest"
ARG IMAGE_BUILD_REVISION="1.0"

ARG CLONEID_URL_WEB=${CLONEID_URL_WEB}
ARG CLONEID_URL_GIT=${CLONEID_URL_GIT}
ARG CLONEID_URL_ZIP=${CLONEID_URL_ZIP}
ARG CLONEID_TAR=${CLONEID_TAR}
ARG CLONEID_HOME=${CLONEID_HOME}
ARG CLONEID_GIT=${CLONEID_GIT}

ARG JAVA_PACKAGE=${JAVA_PACKAGE}

ARG GRADLE_VERSION=8.9
ARG JAVA_VERSION=21.0.3-oracle 
ARG JAVA_HOME=/root/.sdkman/candidates/java/current

ARG CLONEID_MODULE3_PERFORMANCE_TEST_DIR=${CLONEID_MODULE3_PERFORMANCE_TEST_DIR}
ARG CLONEID_MODULE3_PERFORMANCE_TEST_REFERENCE=${CLONEID_MODULE3_PERFORMANCE_TEST_REFERENCE}
ARG CLONEID_MODULE3_PERFORMANCE_TEST_UNIT0=${CLONEID_MODULE3_PERFORMANCE_TEST_UNIT0}
ARG CLONEID_MODULE3_PERFORMANCE_TEST_UNIT1=${CLONEID_MODULE3_PERFORMANCE_TEST_UNIT1}

ENV JAVA_HOME=/root/.sdkman/candidates/java/current
ENV GRADLE_VERSION=8.9
ENV DEBIAN_FRONTEND=noninteractive 
ENV CLONEID_MODULE3_PERFORMANCE_TEST_DIR=${CLONEID_MODULE3_PERFORMANCE_TEST_DIR}
ENV CLONEID_MODULE3_PERFORMANCE_TEST_REFERENCE=${CLONEID_MODULE3_PERFORMANCE_TEST_REFERENCE}
ENV CLONEID_MODULE3_PERFORMANCE_TEST_UNIT0=${CLONEID_MODULE3_PERFORMANCE_TEST_UNIT0}
ENV CLONEID_MODULE3_PERFORMANCE_TEST_UNIT1=${CLONEID_MODULE3_PERFORMANCE_TEST_UNIT1}

ENV IMAGE_AUTHOR_FNAME="${IMAGE_AUTHOR_FNAME}" \
    IMAGE_AUTHOR_LNAME="${IMAGE_AUTHOR_LNAME}" \
    IMAGE_AUTHOR_EMAIL="${IMAGE_AUTHOR_EMAIL}"
    
LABEL IMAGE_maintainer="${IMAGE_AUTHOR_FNAME} ${IMAGE_AUTHOR_LNAME} ${IMAGE_AUTHOR_EMAIL}"
LABEL IMAGE_info=${IMAGE_BUILD_INFO}
LABEL iteration="${IMAGE_BUILD_NAME}_${IMAGE_BUILD_VERSION}_${IMAGE_BUILD_DATE}"

LABEL org.cloneid.module3.image.schema-version="1.0"
LABEL org.cloneid.module3.image.build-date="${IMAGE_BUILD_DATE}"
LABEL org.cloneid.module3.image.name="${IMAGE_BUILD_NAME}"
LABEL org.cloneid.module3.image.description="${IMAGE_BUILD_INFO}"
LABEL org.cloneid.module3.image.url="${CLONEID_URL_WEB}"
LABEL org.cloneid.module3.image.vcs-url="${CLONEID_URL_GIT}"
LABEL org.cloneid.module3.image.authors="${IMAGE_AUTHOR_FNAME} ${IMAGE_AUTHOR_LNAME} ${IMAGE_AUTHOR_EMAIL}"
LABEL org.cloneid.module3.image.vendor="${IMAGE_VENDOR}"
LABEL org.cloneid.module3.image.licenses="${IMAGE_LICENSE}"
LABEL org.cloneid.module3.image.title="${IMAGE_TITLE}"
LABEL org.cloneid.module3.image.version="${IMAGE_BUILD_VERSION}"
LABEL org.cloneid.module3.image.revision="${IMAGE_BUILD_REVISION}"
LABEL org.cloneid.module3.image.architecture="${IMAGE_BUILD_ARCH}"
LABEL org.cloneid.module3.image.docker.cmd="docker run --rm -ti --name ${IMAGE_BUILD_NAME} ${IMAGE_BUILD_NAME}-${IMAGE_BUILD_ARCH}:latest"

SHELL ["/bin/bash", "-c"]

WORKDIR ${CLONEID_HOME}
RUN rm -rf cloneid cloneid-master
# RUN git clone https://github.com/noemiandor/cloneid.git
# # OR
RUN wget ${CLONEID_URL_ZIP} &&  unzip master.zip && mv cloneid-master cloneid && rm master.zip
# # OR
## COPY git/cloneid cloneid

WORKDIR ${CLONEID_HOME}/cloneid

RUN cp gradle/wrapper/gradle-wrapper.properties gradle/wrapper/gradle-wrapper.properties.6
RUN sed -e 's/6.5.1/8.9/' -e "s/https.*distributions\///" < gradle/wrapper/gradle-wrapper.properties.6 > gradle/wrapper/gradle-wrapper.properties

RUN cp build.gradle build.gradle.6
RUN cat build.gradle.6 |sed -e 's/baseName/\/\/ MOVING TO GRADLE 8.9 \/\/ baseName/'  -e 's/archiveClassifier/duplicatesStrategy = DuplicatesStrategy.EXCLUDE\n    archiveClassifier/' > build.gradle

RUN R CMD javareconf
RUN ./gradlew uberJar
RUN cp build/libs/cloneid.jar rpackage/inst/java/cloneid.jar && R CMD build rpackage && R CMD INSTALL ${CLONEID_TAR}

WORKDIR ${CLONEID_MODULE3_PERFORMANCE_TEST_DIR}

ENTRYPOINT service ssh start && ${CLONEID_MODULE3_PERFORMANCE_TEST_REFERENCE} 

HEALTHCHECK NONE
