FROM --platform=${BUILDPLATFORM} rocker/r-ver

ARG IMAGE_BUILD_ARCH=amd64
ARG IMAGE_BUILD_INFO="Cloneid Module3"
ARG IMAGE_BUILD_NAME="cloneid-module3"
ARG IMAGE_BUILD_DATE
ARG IMAGE_BUILD_VERSION="1.0𝛂"
ARG IMAGE_AUTHOR_FNAME="Daniel"
ARG IMAGE_AUTHOR_LNAME="Hannaby"
ARG IMAGE_AUTHOR_EMAIL="<legwork_02land@icloud.com>"
ARG IMAGE_VENDOR="Moffitt"
ARG IMAGE_LICENSE="MIT"
ARG IMAGE_TITLE="${IMAGE_BUILD_NAME}:latest"
ARG IMAGE_BUILD_REVISION="1.0"

ARG CLONEID_URL_WEB="https://www.cloneredesign.com"
ARG CLONEID_URL_GIT="https://github.com/noemiandor/cloneid"

ENV IMAGE_AUTHOR_FNAME="Daniel" \
    IMAGE_AUTHOR_LNAME="Hannaby" \
    IMAGE_AUTHOR_EMAIL="<legwork_02land@icloud.com>"
    
LABEL IMAGE_maintainer="Daniel Hannaby <legwork_02land@icloud.com>"
LABEL IMAGE_info=$IMAGE_BUILD_INFO

LABEL org.cloneid.module3.image.schema-version="1.0"
LABEL org.cloneid.module3.image.build-date="${IMAGE_BUILD_DATE}"
LABEL org.cloneid.module3.image.name="${IMAGE_BUILD_NAME}"
LABEL org.cloneid.module3.image.description="${IMAGE_BUILD_INFO}"
LABEL org.cloneid.module3.image.url="${CLONEID_URL_WEB}"
LABEL org.cloneid.module3.image.vcs-url="${CLONEID_URL_GIT}"
LABEL org.cloneid.module3.image.authors="${IMAGE_AUTHOR_FNAME} ${IMAGE_AUTHOR_LNAME} ${IMAGE_AUTHOR_EMAIL}"
LABEL org.cloneid.module3.image.vendor="${IMAGE_VENDOR}"
LABEL org.cloneid.module3.image.licenses="${IMAGE_LICENSE}"
LABEL org.cloneid.module3.image.title="${IMAGE_TITLE}"
LABEL org.cloneid.module3.image.version="${IMAGE_BUILD_VERSION}"
LABEL org.cloneid.module3.image.revision="${IMAGE_BUILD_REVISION}"
LABEL org.cloneid.module3.image.architecture="${IMAGE_BUILD_ARCH}"
LABEL org.cloneid.module3.image.docker.cmd="docker run --rm -ti --name ${IMAGE_BUILD_NAME} ${IMAGE_BUILD_NAME}-${IMAGE_BUILD_ARCH}:latest"

LABEL iteration="${IMAGE_BUILD_NAME}_${IMAGE_BUILD_VERSION}_${IMAGE_BUILD_DATE}"

ARG CLONEID_HOME=${CLONEID_HOME}
ARG JAVA_PACKAGE=openjdk-11-jdk-headless
ARG JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64

ENV JAVA_HOME=${JAVA_HOME}
ENV DEBIAN_FRONTEND=noninteractive 

RUN apt-get clean all && \
    apt-get update && \
    apt-get upgrade -y && \
    apt-get install -yq \
        libhdf5-dev \
        libcurl4-gnutls-dev \
        libssl-dev \
        libxml2-dev \
        libpng-dev \
        libxt-dev \
        zlib1g-dev \
        libbz2-dev \
        liblzma-dev \
        libglpk40 \
        libgit2-dev \
        ${JAVA_PACKAGE} \
        libmagick++-6.q16-dev \
        libmysqlclient-dev \
        libproj22 \
        libgdal-dev \
        vim \
        git \
        wget \
        virt-what \
    && apt-get clean all && \
    apt-get purge && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN	Rscript -e "install.packages(c('rmarkdown', 'tidyverse', 'workflowr', 'BiocManager'));" && \
	Rscript -e "BiocManager::install(version = '3.19', ask = FALSE)" && \
	Rscript -e "BiocManager::install('biomaRt');" && \
	Rscript -e "install.packages(c( 'qualV', 'RColorBrewer', 'gtools', 'gplots', 'gdata', 'RMySQL', 'flexclust', 'Matrix', 'matlab', 'yaml' ));" && \
	Rscript -e "install.packages(c( 'magick',  'raster' ));" && \
	Rscript -e "install.packages(c( 'ape' ));" && \
	Rscript -e "install.packages(c( 'liayson' ));" && \
	Rscript -e "install.packages(c( 'umap' ));" && \
	Rscript -e "install.packages(c( 'R.utils' ));" && \
	Rscript -e "install.packages(c( 'tictoc' ));" && \
	Rscript -e "install.packages('https://cran.r-project.org/src/contrib/Archive/reticulate/reticulate_1.22.tar.gz',repos=NULL, type='source')" && \
	Rscript -e "install.packages(c( 'rJava' ));"
