mysqlConnection:
  host: localhost
  port: 3306
  user: ""
  password: 
  database: CLONEID
  schemaScript: CLONEID_schema.sql

cellSegmentation:
  input: ~/CellSegmentations/
  output: ~/CellSegmentations/output/
  tmp: ~/Downloads/tmp/
