mysqlConnection:
  host: 
  port: 3306
  user: ""
  password: 
  database: CLONEID
  schemaScript: CLONEID_schema.sql

dbTables:
  - CellLines
  - Freezing
  - Identity
  - Loci
  - Passaging
  - Perspective
