mysqlConnection:
  host: 192.168.1.27
  port: 3306
  user: "root"
  password: "xxxxx"
  database: CLONEID
  schemaScript: CLONEID_schema.sql


cellSegmentation:
  input: ~/CellSegmentations/
  output: ~/CellSegmentations/output/
  tmp: ~/Downloads/tmp/
